#!/bin/bash

#$HOME/.weatherdesk_walls/WeatherDesk-master/camera_modifier.sh &
path="$HOME/.config/weatherdesk_walls"
$path/WeatherDesk-master/WeatherDesk.py -ot4 --no-weather

while ( true )
do
	$path/WeatherDesk-master/WeatherDesk.py -t 4 -o -c Brussels
	sleep 60
done
